{% set version = "2.0.3" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygrib/pygrib-{{ version }}.tar.gz
  sha256: f717adb96f3e2e6a6f52c0b377a57086f187160b104e49f6d96a262c3910e3df

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - ecmwf_grib
    - jasper
    - libpng >=1.6.32,<1.6.35
    - pyproj

  run:
    - python
    - ecmwf_grib
    - jasper
    - libpng >=1.6.32,<1.6.35
    - pyproj
    - numpy

test:
  imports:
    - pygrib
  commands:
    - grib_repack -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Python GRIB (editions 1 and 2) reader.'
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - dopplershift
    - jjhelmus
    - ocefpaf
