{% set version = "2.1.6" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://github.com/jswhit/pygrib/archive/v{{ version }}rel.tar.gz
  sha256: 4466c9b2c8f4e5a45df1fa3b733697bba8e1cc31aba0f8aae8cfd3890e48aae3
  patches:
    - fix-openjpeg-lib.patch  # [win]
    - fix-png-windows.patch  # [win]

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - eccodes
    - jasper
    - openjpeg  # [win]
    - libpng
    - numpy
    - pyproj
    - zlib
  run:
    - python
    - packaging
    - setuptools
    - eccodes
    - jasper
    - openjpeg  # [win]
    - libpng
    - pyproj
    - zlib

test:
  imports:
    - pygrib
  commands:
    - pip check
    - grib_repack -h
  requires:
    - pip

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python GRIB (editions 1 and 2) reader
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - akrherz
    - dopplershift
    - ocefpaf
