schema_version: 1

context:
  version: "2.1.8"

package:
  name: pygrib
  version: ${{ version }}

source:
  url: https://github.com/jswhit/pygrib/archive/v${{ version }}rel.tar.gz
  sha256: 78bae1cf927e3083149a1b618c034882dc980bf5d3375befd93d38fafb5e3a61
  patches:
    - fix-new-cython.patch

build:
  number: 1
  skip: win and vc<14

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - eccodes
    - jasper
    - libpng
    - numpy
    - pyproj
    - zlib
  run:
    - python
    - packaging
    - setuptools
    - eccodes
    - jasper
    - libpng
    - pyproj
    - zlib

tests:
  - python:
      imports:
        - pygrib
      pip_check: true
  - script:
      - if: not win
        then: grib_repack -h

about:
  license: MIT
  license_file: COPYING
  summary: Python GRIB (editions 1 and 2) reader
  homepage: https://github.com/jswhit/pygrib
  repository: https://github.com/jswhit/pygrib
  documentation: https://jswhit.github.io/pygrib/

extra:
  recipe-maintainers:
    - akrherz
    - dopplershift
    - ocefpaf
